services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: on-failure
    environment:
      - NG_APP_API_URL=${NG_APP_API_URL}
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
    ports:
      - '4200:4200'
    networks:
      - quizarena-client-network
    # depends_on:
    #   - backend
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   restart: on-failure
  #   environment:
  #     - SPRING_DATASOURCE_URL=${DATABASE_URL}
  #     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
  #     - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #     - FRONTEND_URL=${FRONTEND_URL}
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./backend/pom.xml
  #       - action: sync+restart
  #         path: ./backend
  #         target: /app
  #         ignore:
  #           - .mvn/
  #           - target/
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - quizarena-maven-repo:/root/.m2
  #   networks:
  #     - quizarena-client-network
  #     - quizarena-server-network
  #   depends_on:
  #     - database

#   database:
#     image: postgres:latest
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     ports:
#       - '5432:5432'
#     volumes:
#       - quizarena-postgresql-data:/var/lib/postgresql/data
#     networks:
#       - quizarena-server-network

networks:
  quizarena-client-network:
# volumes:
#   quizarena-postgresql-data:
#   quizarena-maven-repo:
