services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - NG_APP_API_URL=${NG_APP_API_URL}
      - NG_APP_WS_URL=${NG_APP_WS_URL}
      - NG_APP_KEYCLOAK_AUTHORITY=${NG_APP_KEYCLOAK_AUTHORITY}
      - NG_APP_KEYCLOAK_CLIENT_ID=${NG_APP_KEYCLOAK_CLIENT_ID}
      - NG_APP_KEYCLOAK_REALM=${NG_APP_KEYCLOAK_REALM}
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
    ports:
      - '4200:4200'
    networks:
      - quizarena-client-network
    depends_on:
      - apigateway

  apigateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '8085:8085'
    networks:
      - quizarena-server-network
      - quizarena-client-network
    develop:
      watch:
        - action: sync+restart
          path: ./backend/Gateway
          target: /opt/
    depends_on:
      - user-service
      - quiz-service

  user-service:
    build:
      context: ./backend/UserService
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - quizarena-server-network
    ports:
      - '8086:8086'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    develop:
      watch:
        - action: rebuild
          path: ./backend/UserService/build.gradle.kts
        - action: sync+restart
          path: ./backend/UserService
          target: /opt/
    depends_on:
      - database

  quiz-service:
    build:
      context: ./backend/QuizService
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    develop:
      watch:
        - action: rebuild
          path: ./backend/QuizService/build.gradle.kts
        - action: sync+restart
          path: ./backend/QuizService
          target: /opt
    ports:
      - '8087:8087'
    networks:
      - quizarena-server-network
    depends_on:
      - database

  # keycloak:
  #   build:
  #     context: ./backend/Keycloak/data
  #     dockerfile: Dockerfile.kc
  #   restart: always
  #   environment:
  #     - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
  #     - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
  #     - KC_HOSTNAME=${KC_HOSTNAME}
  #     - KC_HTTP_PORT=8080
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - quizarena-server-network
  #     - quizarena-client-network

  database:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - quizarena-postgresql-data:/var/lib/postgresql/data
    networks:
      - quizarena-server-network
  game-service:
    build:
      context: ./backend/gameservice
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '8088:8088'
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SERVICES_USERSERVICE_URL=http://gateway:8085/users
      - SERVICES_QUIZSERVICE_URL=http://gateway:8085/quizzes
      - FRONTEND_URL=${FRONTEND_URL}
    develop:
      watch:
        - action: rebuild
          path: ./backend/gameservice/pom.xml
        - action: sync+restart
          path: ./backend/gameservice
          target: /opt
    depends_on:
      - redis-server
    networks:
      - quizarena-server-network
  redis-server:
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - quizarena-server-network
networks:
  quizarena-server-network:
    name: quizarena-server-network
  quizarena-client-network:
    name: quizarena-client-network
volumes:
  quizarena-postgresql-data:
