services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - NG_APP_API_URL=${NG_APP_API_URL}
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
    ports:
      - '4200:4200'
    networks:
      - quizarena-client-network
    # depends_on:
    #   - gateway # Gateway will run on port 8080

  apigateway:
    build:
      context: ./backend/Gateway
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - user-service
      - quiz-service
      # - keycloak
    ports:
      - "8085:8085"
    networks:
      - quizarena-server-network
      - quizarena-client-network
    develop:
      watch:
        - action: sync+restart
          path: ./backend/Gateway
          target: /opt/

  user-service:
    build:
      context: ./backend/UserService
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - quizarena-server-network
    ports:
      - "8086:8086" 
    depends_on:
      - database
      # - keycloak
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    develop:
      watch:
        - action: sync+restart
          path: ./backend/UserService
          target: /opt/

  quiz-service:
    build:
      context: ./backend/QuizService
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    develop:
      watch:
        - action: rebuild
          path: ./backend/QuizService/build.gradle.kts
        - action: sync+restart
          path: ./backend/QuizService
          target: /opt
    ports:
      - '8081:8081'
    networks:
      - quizarena-server-network
    depends_on:
      - database

  keycloak:
    build:
      context: ./backend/Keycloak/data
      dockerfile: Dockerfile.kc
    restart: always
    ports:
      - 8080:8080
    networks:
      - quizarena-server-network
      - quizarena-client-network
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8080
      # - KC_HOSTNAME=keycloak
      - KC_HOSTNAME=localhost
      # - KC_HOSTNAME_STRICT=false
      # - KC_HOSTNAME_STRICT_HTTPS=false


  database:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - quizarena-postgresql-data:/var/lib/postgresql/data
    networks:
      - quizarena-server-network

networks:
  quizarena-client-network:
  quizarena-server-network:
volumes:
  quizarena-postgresql-data:
