services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NG_APP_API_URL: ${NG_APP_API_URL}
    ports:
      - '4000:4000'
    networks:
      - quizarena-client-network

networks:
  quizarena-client-network:
