services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - NG_APP_API_URL=${NG_APP_API_URL}
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
    ports:
      - '4200:4200'
    networks:
      - quizarena-client-network
    # depends_on:
    #   - gateway # Gateway will run on port 8080
  quiz-service:
    build:
      context: ./backend/QuizService
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    develop:
      watch:
        - action: rebuild
          path: ./backend/QuizService/build.gradle.kts
        - action: sync+restart
          path: ./backend/QuizService
          target: /opt
    ports:
      - '8081:8080'
    networks:
      - quizarena-server-network
    depends_on:
      - database

  database:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - quizarena-postgresql-data:/var/lib/postgresql/data
    networks:
      - quizarena-server-network
  gameservice:
    build:
      context: ./backend/gameservice
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '8088:8088'
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SERVICES_USERSERVICE_URL=http://gateway:8085/users
      - SERVICES_QUIZSERVICE_URL=http://gateway:8085/quiz
    depends_on:
      - redis-server
    networks:
      - quizarena-server-network
  redis-server:
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - quizarena-server-network
networks:
  quizarena-client-network:
  quizarena-server-network:
volumes:
  quizarena-postgresql-data:
