spring:
  application:
    name: userservice
  profiles:
    active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://keycloak:8080/realms/quizarena
  #         jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

app:
  keycloak:
    admin:
      clientId: quizarena-rest-api
      clientSecret: iDmNXc7fMcUBLMUm4tyVPkv0FTAjtQBN
    realm: quizarena
    serverUrl: http://keycloak:8080

server:
  port: 8086
