services:
  keycloak:
    build:
      context: ./data
      dockerfile: Dockerfile.kc
    restart: always
    ports:
      - '8080:8080'
    networks:
      - quizarena-network
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_HTTP_PORT=8080

networks:
  quizarena-network:
    name: quizarena-network